twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - bootstrap_5_layout.html.twig
    globals:
        hcaptcha_site_key: '%env(HCAPTCHA_SITEKEY)%'
when@test:
    twig:
        strict_variables: true
